# Generated by Django 4.2.3 on 2023-07-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=40)),
                ('book_author', models.CharField(max_length=30)),
                ('book_desc', models.TextField()),
            ],
        ),
    ]
