# Generated by Django 4.2.3 on 2023-07-26 12:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('route_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('route_name', models.CharField(max_length=50)),
                ('route_origin', models.CharField(max_length=30)),
                ('route_destination', models.CharField(max_length=30)),
                ('stops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
    ]
