# Generated by Django 4.2.3 on 2023-07-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('trip_id', models.CharField(max_length=10)),
                ('traveller_name', models.CharField(max_length=30)),
                ('ticket_cost', models.PositiveSmallIntegerField(default=0)),
                ('traveller_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
