# Generated by Django 4.2.3 on 2023-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='traveller_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
