# Generated by Django 4.2.3 on 2023-07-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_traveller_number_alter_booking_ticket_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
